add_newline = true
scan_timeout = 10

[os]
format = '\[[$symbol]($style)\]'
style = "bold green"
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
symbol = "󱗾 "
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
min_time = 500
format = '\[[󱎫 $duration](bold yellow)\]'


[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'


[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'


[git_branch]
symbol = '󰊢 '
format = '\[[$symbol$branch]($style)\]'

[git_status]
ahead = '󱞿 ${count}'
diverged = '󱞿 ${ahead_count} 󱞣 ${behind_count}'
staged = ' ${count}'
behind = "󱞣 ${count}"

[memory_usage]
symbol = "󰍛 "
format = '\[$symbol[$ram( | $swap)]($style)\]'
disabled = false

[nodejs]
symbol = "󰌞 "
format = '\[[$symbol($version)]($style)\]'


[package]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
style = "bold yellow"
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
symbol = "󱘗 "
format = '\[[$symbol($version)]($style)\]'

[sudo]
format = '\[[sudo 󰦣]($style)\]'
disabled = false

[username]
format = '\[[$user]($style)\]'